[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "contracts/atomic-swap", "contracts/cross-chain-swap"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "solidity-utils/=contracts/cross-chain-swap/lib/solidity-utils/",
    "limit-order-protocol/=contracts/cross-chain-swap/lib/limit-order-protocol/",
    "limit-order-settlement/=contracts/cross-chain-swap/lib/limit-order-settlement/",
    "murky/=contracts/cross-chain-swap/lib/murky/",
    "forge-std/=lib/forge-std/src/"
]
auto_detect_remappings = true
optimizer = true
optimizer_runs = 200
ignore_compile_errors = true

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
