/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface XMREscrowFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addressOfSrcEscrow"
      | "createSrcEscrow"
      | "srcImplementation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addressOfSrcEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createSrcEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "srcImplementation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addressOfSrcEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSrcEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "srcImplementation",
    data: BytesLike
  ): Result;
}

export interface XMREscrowFactory extends BaseContract {
  connect(runner?: ContractRunner | null): XMREscrowFactory;
  waitForDeployment(): Promise<this>;

  interface: XMREscrowFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addressOfSrcEscrow: TypedContractMethod<[salt: BytesLike], [string], "view">;

  createSrcEscrow: TypedContractMethod<
    [salt: BytesLike],
    [string],
    "nonpayable"
  >;

  srcImplementation: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addressOfSrcEscrow"
  ): TypedContractMethod<[salt: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "createSrcEscrow"
  ): TypedContractMethod<[salt: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "srcImplementation"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
