/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IBaseEscrow {
  export type ImmutablesStruct = {
    orderHash: BytesLike;
    hashlock: BytesLike;
    maker: BigNumberish;
    taker: BigNumberish;
    token: BigNumberish;
    amount: BigNumberish;
    safetyDeposit: BigNumberish;
    timelocks: BigNumberish;
  };

  export type ImmutablesStructOutput = [
    orderHash: string,
    hashlock: string,
    maker: bigint,
    taker: bigint,
    token: bigint,
    amount: bigint,
    safetyDeposit: bigint,
    timelocks: bigint
  ] & {
    orderHash: string;
    hashlock: string;
    maker: bigint;
    taker: bigint;
    token: bigint;
    amount: bigint;
    safetyDeposit: bigint;
    timelocks: bigint;
  };
}

export interface XMREscrowSrcInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FACTORY"
      | "PROXY_BYTECODE_HASH"
      | "RESCUE_DELAY"
      | "cancel"
      | "deposit"
      | "publicWithdraw"
      | "rescueFunds"
      | "swapAdapter"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "EscrowCancelled"
      | "EscrowWithdrawal"
      | "FundsRescued"
  ): EventFragment;

  encodeFunctionData(functionFragment: "FACTORY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PROXY_BYTECODE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESCUE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [IBaseEscrow.ImmutablesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BytesLike, BytesLike, IBaseEscrow.ImmutablesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "publicWithdraw",
    values: [BytesLike, IBaseEscrow.ImmutablesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueFunds",
    values: [AddressLike, BigNumberish, IBaseEscrow.ImmutablesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, IBaseEscrow.ImmutablesStruct]
  ): string;

  decodeFunctionResult(functionFragment: "FACTORY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PROXY_BYTECODE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESCUE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositEvent {
  export type InputTuple = [
    sender: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    hashlock: BytesLike
  ];
  export type OutputTuple = [
    sender: string,
    token: string,
    amount: bigint,
    hashlock: string
  ];
  export interface OutputObject {
    sender: string;
    token: string;
    amount: bigint;
    hashlock: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowWithdrawalEvent {
  export type InputTuple = [secret: BytesLike];
  export type OutputTuple = [secret: string];
  export interface OutputObject {
    secret: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsRescuedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XMREscrowSrc extends BaseContract {
  connect(runner?: ContractRunner | null): XMREscrowSrc;
  waitForDeployment(): Promise<this>;

  interface: XMREscrowSrcInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FACTORY: TypedContractMethod<[], [string], "view">;

  PROXY_BYTECODE_HASH: TypedContractMethod<[], [string], "view">;

  RESCUE_DELAY: TypedContractMethod<[], [bigint], "view">;

  cancel: TypedContractMethod<
    [immutables: IBaseEscrow.ImmutablesStruct],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [
      hashlock: BytesLike,
      claimCommitment: BytesLike,
      refundCommitment: BytesLike,
      immutables: IBaseEscrow.ImmutablesStruct
    ],
    [void],
    "payable"
  >;

  publicWithdraw: TypedContractMethod<
    [secret: BytesLike, immutables: IBaseEscrow.ImmutablesStruct],
    [void],
    "nonpayable"
  >;

  rescueFunds: TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      immutables: IBaseEscrow.ImmutablesStruct
    ],
    [void],
    "nonpayable"
  >;

  swapAdapter: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [secret: BytesLike, immutables: IBaseEscrow.ImmutablesStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FACTORY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROXY_BYTECODE_HASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RESCUE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<
    [immutables: IBaseEscrow.ImmutablesStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      hashlock: BytesLike,
      claimCommitment: BytesLike,
      refundCommitment: BytesLike,
      immutables: IBaseEscrow.ImmutablesStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "publicWithdraw"
  ): TypedContractMethod<
    [secret: BytesLike, immutables: IBaseEscrow.ImmutablesStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueFunds"
  ): TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      immutables: IBaseEscrow.ImmutablesStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [secret: BytesLike, immutables: IBaseEscrow.ImmutablesStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCancelled"
  ): TypedContractEvent<
    EscrowCancelledEvent.InputTuple,
    EscrowCancelledEvent.OutputTuple,
    EscrowCancelledEvent.OutputObject
  >;
  getEvent(
    key: "EscrowWithdrawal"
  ): TypedContractEvent<
    EscrowWithdrawalEvent.InputTuple,
    EscrowWithdrawalEvent.OutputTuple,
    EscrowWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "FundsRescued"
  ): TypedContractEvent<
    FundsRescuedEvent.InputTuple,
    FundsRescuedEvent.OutputTuple,
    FundsRescuedEvent.OutputObject
  >;

  filters: {
    "Deposit(address,address,uint256,bytes32)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "EscrowCancelled()": TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;
    EscrowCancelled: TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;

    "EscrowWithdrawal(bytes32)": TypedContractEvent<
      EscrowWithdrawalEvent.InputTuple,
      EscrowWithdrawalEvent.OutputTuple,
      EscrowWithdrawalEvent.OutputObject
    >;
    EscrowWithdrawal: TypedContractEvent<
      EscrowWithdrawalEvent.InputTuple,
      EscrowWithdrawalEvent.OutputTuple,
      EscrowWithdrawalEvent.OutputObject
    >;

    "FundsRescued(address,uint256)": TypedContractEvent<
      FundsRescuedEvent.InputTuple,
      FundsRescuedEvent.OutputTuple,
      FundsRescuedEvent.OutputObject
    >;
    FundsRescued: TypedContractEvent<
      FundsRescuedEvent.InputTuple,
      FundsRescuedEvent.OutputTuple,
      FundsRescuedEvent.OutputObject
    >;
  };
}
